### ISSUE TITLE
Mac Build? Has Issues...

### ISSUE THREAD

**Issue by Andres-M-Rios** [dikhim/uselessclicker#1]
Not sure what to run? (How to run) on a MAC. What command line on windows machine would start up the program? I'll start from there and help you out to get a running MAC edition if you would like for this Open Project. Thanks! :)

**Comment by dikhim** [comment]
Hi. Thanks for the feedback. Really appreciate this.
So. If you downloaded the standalone version, zip archive, there is only one exec file in root folder. 
I managed to run it via the terminal

- Right-click your file and select "Open with" 
- Type in the search field "terminal"
- Select terminal application and mark always open it in this application

After that it starts just for double click. There still be that horrible terminal window, but it should work fine

For jar file it should work as it is, if you have java 8. It won't work if you have java 11 or newer :/
Write a reply does it work or not. And if it doesn't, send the terminal log too
